# Generated by Django 4.2 on 2023-05-24 10:57

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0004_company_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="employee",
            name="date_of_hire",
        ),
    ]
