# Generated by Django 4.2 on 2023-05-25 23:53

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0005_remove_employee_date_of_hire"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="department",
            name="cost_center",
        ),
        migrations.CreateModel(
            name="CostCenter",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("code", models.CharField(max_length=10)),
                ("description", models.TextField()),
                ("budget", models.DecimalField(decimal_places=2, default=Decimal("0"), max_digits=10)),
                ("planned_expenses", models.DecimalField(decimal_places=2, default=Decimal("0"), max_digits=10)),
                ("actual_expenses", models.DecimalField(decimal_places=2, default=Decimal("0"), max_digits=10)),
                ("created_at", models.DateField(auto_now_add=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="cost_centers", to="core.company"
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="cost_centers", to="core.department"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
